services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chat-llm-com-rag
    stdin_open: true
    tty: true
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    restart: unless-stopped
